import type { ModuleId } from './types';

export interface Flashcard {
  id: string;
  deck: ModuleId;
  topic: string;
  front: string;
  back: string;
}

const t = String.raw;

const M1: Omit<Flashcard, 'deck'>[] = [
  { id: 'm1-trig30', topic: 'M5', front: t`$\sin 30^\circ,\ \cos 30^\circ,\ \tan 30^\circ$`, back: t`$\tfrac12,\quad \tfrac{\sqrt3}{2},\quad \tfrac{1}{\sqrt3} = \tfrac{\sqrt3}{3}$` },
  { id: 'm1-trig45', topic: 'M5', front: t`$\sin 45^\circ,\ \cos 45^\circ,\ \tan 45^\circ$`, back: t`$\tfrac{\sqrt2}{2},\quad \tfrac{\sqrt2}{2},\quad 1$` },
  { id: 'm1-trig60', topic: 'M5', front: t`$\sin 60^\circ,\ \cos 60^\circ,\ \tan 60^\circ$`, back: t`$\tfrac{\sqrt3}{2},\quad \tfrac12,\quad \sqrt3$` },
  { id: 'm1-interior', topic: 'M5', front: t`Sum of the interior angles of an $n$-sided polygon`, back: t`$(n - 2) \times 180^\circ$` },
  { id: 'm1-exterior', topic: 'M5', front: t`Each exterior angle of a regular $n$-gon`, back: t`$\dfrac{360^\circ}{n}$ (exterior angles always sum to $360^\circ$)` },
  { id: 'm1-centre', topic: 'M5', front: 'Angle at the centre vs angle at the circumference (same arc)', back: 'The angle at the centre is twice the angle at the circumference.' },
  { id: 'm1-altseg', topic: 'M5', front: 'Alternate segment theorem', back: 'The angle between a tangent and a chord equals the angle in the alternate segment.' },
  { id: 'm1-cyclic', topic: 'M5', front: 'Opposite angles of a cyclic quadrilateral', back: t`Sum to $180^\circ$.` },
  { id: 'm1-tangent', topic: 'M5', front: 'Angle between a tangent and the radius at the point of contact', back: t`$90^\circ$` },
  { id: 'm1-trapezium', topic: 'M5', front: t`Area of a trapezium with parallel sides $a$, $b$ and height $h$`, back: t`$\tfrac12(a + b)h$` },
  { id: 'm1-sphere', topic: 'M5', front: 'Volume and surface area of a sphere', back: t`$V = \tfrac43\pi r^3,\quad A = 4\pi r^2$ (given in the exam if needed)` },
  { id: 'm1-cone', topic: 'M5', front: 'Volume of a cone or pyramid', back: t`$\tfrac13 \times \text{base area} \times \text{height}$` },
  { id: 'm1-arc', topic: 'M5', front: t`Arc length and sector area for an angle $\theta$ in degrees`, back: t`$\dfrac{\theta}{360}\times 2\pi r$ and $\dfrac{\theta}{360}\times\pi r^2$` },
  { id: 'm1-similar', topic: 'M3', front: t`Similar shapes with length scale factor $k$: areas and volumes`, back: t`Areas $\times k^2$, volumes $\times k^3$` },
  { id: 'm1-diag3d', topic: 'M5', front: t`Space diagonal of an $a \times b \times c$ cuboid`, back: t`$\sqrt{a^2 + b^2 + c^2}$` },
  { id: 'm1-equilateral', topic: 'M5', front: t`Area of an equilateral triangle of side $a$`, back: t`$\tfrac{\sqrt3}{4}a^2$` },
  { id: 'm1-quadformula', topic: 'M4', front: t`Roots of $ax^2 + bx + c = 0$`, back: t`$x = \dfrac{-b \pm \sqrt{b^2 - 4ac}}{2a}$` },
  { id: 'm1-completesq', topic: 'M4', front: t`Complete the square: $x^2 + bx + c$`, back: t`$\left(x + \tfrac b2\right)^2 + c - \tfrac{b^2}{4}$, turning point $\left(-\tfrac b2,\ c - \tfrac{b^2}{4}\right)$` },
  { id: 'm1-dots', topic: 'M4', front: 'Difference of two squares', back: t`$a^2 - b^2 = (a - b)(a + b)$` },
  { id: 'm1-quadseq', topic: 'M4', front: t`In the sequence $an^2 + bn + c$, the second difference is…`, back: t`$2a$` },
  { id: 'm1-perp', topic: 'M4', front: t`Gradient of a line perpendicular to one of gradient $m$`, back: t`$-\dfrac1m$` },
  { id: 'm1-fd', topic: 'M6', front: 'Frequency density', back: t`$\dfrac{\text{frequency}}{\text{class width}}$: in a histogram, frequency is the area.` },
  { id: 'm1-cfmedian', topic: 'M6', front: t`On a cumulative frequency graph for $n$ values, read the median and quartiles at…`, back: t`$\tfrac n2$ for the median, $\tfrac n4$ and $\tfrac{3n}{4}$ for the quartiles` },
  { id: 'm1-or', topic: 'M7', front: t`$P(A \text{ or } B)$ in general`, back: t`$P(A) + P(B) - P(A \text{ and } B)$` },
  { id: 'm1-cond', topic: 'M7', front: t`Conditional probability $P(A \mid B)$`, back: t`$\dfrac{P(A \text{ and } B)}{P(B)}$. Fastest method: imagine 1000 people and use frequencies.` },
  { id: 'm1-litres', topic: 'M1', front: t`$1\ \text{m}^3$ in litres and in $\text{cm}^3$`, back: t`$1000$ litres $= 10^6\ \text{cm}^3$` },
  { id: 'm1-density', topic: 'M1', front: t`$1\ \text{g cm}^{-3}$ in $\text{kg m}^{-3}$`, back: t`$1000\ \text{kg m}^{-3}$` },
  { id: 'm1-kmh', topic: 'M1', front: t`Convert $\text{km h}^{-1}$ to $\text{m s}^{-1}$`, back: t`Divide by 3.6 (so $36\ \text{km h}^{-1} = 10\ \text{m s}^{-1}$)` },
  { id: 'm1-hcflcm', topic: 'M2', front: t`$\operatorname{HCF}(a, b) \times \operatorname{LCM}(a, b) = {?}$`, back: t`$ab$` },
  { id: 'm1-factors', topic: 'M2', front: t`Number of factors of $p^a q^b r^c$`, back: t`$(a + 1)(b + 1)(c + 1)$` },
  { id: 'm1-rationalise', topic: 'M2', front: t`Rationalise $\dfrac{1}{\sqrt a - \sqrt b}$`, back: t`$\dfrac{\sqrt a + \sqrt b}{a - b}$` },
  { id: 'm1-recur', topic: 'M2', front: t`$0.\dot{0}\dot{1}$ and $0.\dot{1}$ as fractions`, back: t`$\tfrac{1}{99}$ and $\tfrac19$` },
  { id: 'm1-bounds', topic: 'M2', front: t`Upper bound of $a - b$ and of $\tfrac ab$`, back: t`$a_{\max} - b_{\min}$ and $\dfrac{a_{\max}}{b_{\min}}$` },
  { id: 'm1-reverse', topic: 'M3', front: 'After a 20% increase a price is £60. What was it before?', back: t`$60 \div 1.2 = £50$ (not $60 \times 0.8$)` },
];

const M2: Omit<Flashcard, 'deck'>[] = [
  { id: 'm2-disc', topic: 'MM1', front: t`Discriminant of $ax^2 + bx + c$ and what it tells you`, back: t`$b^2 - 4ac$: $>0$ two distinct real roots, $=0$ one repeated root, $<0$ none` },
  { id: 'm2-alwayspos', topic: 'MM1', front: t`When is $ax^2 + bx + c > 0$ for every $x$?`, back: t`When $a > 0$ and $b^2 - 4ac < 0$` },
  { id: 'm2-remainder', topic: 'MM1', front: t`Remainder when $p(x)$ is divided by $(x - a)$`, back: t`$p(a)$. If $p(a) = 0$, $(x - a)$ is a factor.` },
  { id: 'm2-remquad', topic: 'MM1', front: 'Remainder when dividing a polynomial by a quadratic', back: t`Linear, $rx + s$: find $r, s$ by substituting the roots of the divisor.` },
  { id: 'm2-ap', topic: 'MM2', front: t`Sum of the first $n$ terms of an arithmetic series`, back: t`$\tfrac n2\big(2a + (n - 1)d\big) = \tfrac n2(a + \ell)$` },
  { id: 'm2-gp', topic: 'MM2', front: t`Sum of the first $n$ terms of a geometric series`, back: t`$\dfrac{a(1 - r^n)}{1 - r}$` },
  { id: 'm2-sinf', topic: 'MM2', front: 'Sum to infinity of a geometric series', back: t`$\dfrac{a}{1 - r}$, only when $|r| < 1$` },
  { id: 'm2-ncr', topic: 'MM2', front: t`$\dbinom nr$`, back: t`$\dfrac{n!}{r!\,(n - r)!}$` },
  { id: 'm2-sumn', topic: 'MM2', front: t`$1 + 2 + 3 + \cdots + n$`, back: t`$\dfrac{n(n + 1)}{2}$` },
  { id: 'm2-un', topic: 'MM2', front: t`Get the $n$th term from the sum formula $S_n$`, back: t`$u_n = S_n - S_{n-1}$` },
  { id: 'm2-circle', topic: 'MM3', front: t`Centre and radius of $x^2 + y^2 + cx + dy + e = 0$`, back: t`Centre $\left(-\tfrac c2, -\tfrac d2\right)$, radius $\sqrt{\tfrac{c^2}{4} + \tfrac{d^2}{4} - e}$` },
  { id: 'm2-tanlen', topic: 'MM3', front: t`Length of the tangent from an external point $P$ to a circle`, back: t`$\sqrt{CP^2 - r^2}$` },
  { id: 'm2-sinerule', topic: 'MM4', front: 'Sine rule', back: t`$\dfrac{a}{\sin A} = \dfrac{b}{\sin B} = \dfrac{c}{\sin C}$` },
  { id: 'm2-cosrule', topic: 'MM4', front: 'Cosine rule', back: t`$a^2 = b^2 + c^2 - 2bc\cos A$` },
  { id: 'm2-area', topic: 'MM4', front: 'Area of a triangle from two sides and the included angle', back: t`$\tfrac12ab\sin C$` },
  { id: 'm2-rad', topic: 'MM4', front: t`Arc length and sector area with $\theta$ in radians`, back: t`$s = r\theta,\quad A = \tfrac12 r^2\theta$` },
  { id: 'm2-segment', topic: 'MM4', front: t`Area of a segment ($\theta$ in radians)`, back: t`$\tfrac12 r^2(\theta - \sin\theta)$` },
  { id: 'm2-pyth', topic: 'MM4', front: 'The two identities in the ESAT specification', back: t`$\tan\theta = \dfrac{\sin\theta}{\cos\theta}$ and $\sin^2\theta + \cos^2\theta = 1$` },
  { id: 'm2-periods', topic: 'MM4', front: 'Periods of sin, cos and tan', back: t`$2\pi,\ 2\pi,\ \pi$` },
  { id: 'm2-loglaws', topic: 'MM5', front: 'Laws of logarithms', back: t`$\log xy = \log x + \log y$, $\;\log\tfrac xy = \log x - \log y$, $\;\log x^k = k\log x$` },
  { id: 'm2-logspecial', topic: 'MM5', front: t`$\log_a 1$, $\;\log_a a$, $\;\log_a\tfrac1x$`, back: t`$0$, $\;1$, $\;-\log_a x$` },
  { id: 'm2-expgraph', topic: 'MM5', front: t`Key features of $y = a^x$ ($a > 0$)`, back: t`Passes through $(0, 1)$, asymptote $y = 0$, always positive` },
  { id: 'm2-diff', topic: 'MM6', front: t`$\dfrac{\mathrm{d}}{\mathrm{d}x}\,x^n$`, back: t`$nx^{n-1}$ (for any rational $n$)` },
  { id: 'm2-normal', topic: 'MM6', front: t`Gradient of the normal where the tangent gradient is $m$`, back: t`$-\dfrac1m$` },
  { id: 'm2-nature', topic: 'MM6', front: 'Second-derivative test for a stationary point', back: t`$f'' > 0$: minimum; $f'' < 0$: maximum` },
  { id: 'm2-int', topic: 'MM7', front: t`$\displaystyle\int x^n\,\mathrm{d}x$`, back: t`$\dfrac{x^{n+1}}{n + 1} + c$ (for $n \ne -1$)` },
  { id: 'm2-ftc', topic: 'MM7', front: t`$\dfrac{\mathrm{d}}{\mathrm{d}x}\displaystyle\int_a^x f(t)\,\mathrm{d}t$`, back: t`$f(x)$` },
  { id: 'm2-trap', topic: 'MM7', front: t`Trapezium rule with strip width $h$`, back: t`$\tfrac h2\left[y_0 + 2(y_1 + \cdots + y_{n-1}) + y_n\right]$` },
  { id: 'm2-trapover', topic: 'MM7', front: 'When does the trapezium rule overestimate?', back: 'When the curve bends upwards (convex, like x²). It underestimates for curves that bend downwards.' },
  { id: 'm2-area-int', topic: 'MM7', front: 'Integral vs area when the curve goes below the axis', back: 'The integral counts area below the axis as negative. Split at the roots and add absolute values for the total area.' },
  { id: 'm2-shift', topic: 'MM8', front: t`$y = f(x + a)$ is $y = f(x)$ moved…`, back: t`Left by $a$` },
  { id: 'm2-stretch', topic: 'MM8', front: t`$y = f(ax)$ is $y = f(x)$…`, back: t`Stretched horizontally by factor $\tfrac1a$ (squashed if $a > 1$)` },
  { id: 'm2-negstretch', topic: 'MM8', front: t`What happens to a maximum point under $y = -2f(x)$?`, back: t`It becomes a minimum, with the $y$-coordinate multiplied by $-2$` },
  { id: 'm2-cubicroots', topic: 'MM8', front: 'When does a cubic have three distinct real roots?', back: 'When its local maximum value is positive and its local minimum value is negative.' },
];

const PH: Omit<Flashcard, 'deck'>[] = [
  { id: 'ph-q', topic: 'P1', front: 'Current in terms of charge', back: t`$I = \dfrac Qt$` },
  { id: 'ph-v', topic: 'P1', front: 'Voltage in terms of energy and charge', back: t`$V = \dfrac EQ$` },
  { id: 'ph-p', topic: 'P1', front: 'Three forms of electrical power', back: t`$P = IV = I^2R = \dfrac{V^2}{R}$` },
  { id: 'ph-parallel', topic: 'P1', front: 'Two resistors in parallel', back: t`$R = \dfrac{R_1R_2}{R_1 + R_2}$, less than either resistor` },
  { id: 'ph-ntc', topic: 'P1', front: 'NTC thermistor and LDR behaviour', back: 'Thermistor: resistance falls as temperature rises. LDR: resistance falls as light increases.' },
  { id: 'ph-lamp', topic: 'P1', front: 'Shape of a filament lamp I–V graph and why', back: 'A curve that flattens: the filament heats up, so its resistance increases with current.' },
  { id: 'ph-mah', topic: 'P1', front: '1 mAh in coulombs', back: t`$10^{-3} \times 3600 = 3.6$ C` },
  { id: 'ph-bil', topic: 'P2', front: 'Force on a current-carrying wire perpendicular to a field', back: t`$F = BIL$` },
  { id: 'ph-flhr', topic: 'P2', front: 'Fleming’s left-hand rule', back: 'First finger: Field. seCond finger: Current. thuMb: Motion (force).' },
  { id: 'ph-transformer', topic: 'P2', front: 'Transformer equations', back: t`$\dfrac{V_p}{V_s} = \dfrac{n_p}{n_s}$ and (ideal) $V_pI_p = V_sI_s$` },
  { id: 'ph-transmission', topic: 'P2', front: 'Why is power transmitted at high voltage?', back: t`For the same power the current is lower, so the $I^2R$ losses in the cables are much smaller.` },
  { id: 'ph-induction', topic: 'P2', front: 'Three ways to increase an induced voltage', back: 'Move faster, use a stronger magnet (field), use more turns of wire.' },
  { id: 'ph-suvat', topic: 'P3', front: 'The constant-acceleration equations', back: t`$v = u + at,\ \ s = ut + \tfrac12at^2,\ \ v^2 = u^2 + 2as,\ \ s = \tfrac12(u + v)t$` },
  { id: 'ph-vt', topic: 'P3', front: 'Gradient and area of a velocity–time graph', back: 'Gradient = acceleration; area = displacement.' },
  { id: 'ph-impulse', topic: 'P3', front: 'Force and momentum', back: t`$F = \dfrac{\Delta p}{\Delta t}$; momentum $p = mv$ is conserved in collisions and explosions` },
  { id: 'ph-kep', topic: 'P3', front: 'Kinetic energy in terms of momentum', back: t`$E_k = \dfrac{p^2}{2m}$` },
  { id: 'ph-power', topic: 'P3', front: t`Power of a force moving at speed $v$`, back: t`$P = Fv$` },
  { id: 'ph-eff', topic: 'P3', front: 'Efficiency', back: t`$\dfrac{\text{useful output}}{\text{total input}} \times 100\%$` },
  { id: 'ph-hooke', topic: 'P3', front: 'Hooke’s law and elastic energy', back: t`$F = kx$, $\;E = \tfrac12Fx = \tfrac12kx^2$` },
  { id: 'ph-terminal', topic: 'P3', front: 'Condition for terminal velocity', back: 'Drag equals weight (resultant force zero).' },
  { id: 'ph-lift', topic: 'P3', front: 'Reading on scales in an accelerating lift (up positive)', back: t`$R = m(g + a)$` },
  { id: 'ph-g', topic: 'P3', front: t`Value of $g$ in the ESAT`, back: t`$10\ \text{N kg}^{-1}$` },
  { id: 'ph-shc', topic: 'P4', front: 'Specific heat capacity equation', back: t`$E = mc\Delta\theta$` },
  { id: 'ph-radiation', topic: 'P4', front: 'Best and worst emitters and absorbers of infrared', back: 'Matt black: best at both. Shiny silver: worst at both.' },
  { id: 'ph-latent', topic: 'P5', front: 'Specific latent heat equation', back: t`$E = mL$ (temperature constant during the change of state)` },
  { id: 'ph-hydro', topic: 'P5', front: t`Pressure at depth $h$ in a liquid`, back: t`$p = p_{\text{atm}} + \rho gh$` },
  { id: 'ph-boyle', topic: 'P5', front: 'Boyle’s law', back: t`$pV = \text{constant}$ (fixed mass, constant temperature)` },
  { id: 'ph-mixdensity', topic: 'P5', front: 'Density of a mixture', back: 'Total mass ÷ total volume (not the average of the densities).' },
  { id: 'ph-wave', topic: 'P6', front: 'Wave equation; what stays constant at a boundary?', back: t`$v = f\lambda$; the frequency stays constant` },
  { id: 'ph-refract', topic: 'P6', front: 'A wave slows down crossing a boundary. Which way does it bend?', back: 'Towards the normal.' },
  { id: 'ph-hearing', topic: 'P6', front: 'Range of human hearing', back: '20 Hz to 20 kHz. Ultrasound is above 20 kHz.' },
  { id: 'ph-em', topic: 'P6', front: 'EM spectrum in order of increasing frequency', back: 'Radio, microwave, infrared, visible, ultraviolet, X-ray, gamma.' },
  { id: 'ph-c', topic: 'P6', front: 'Speed of light in a vacuum', back: t`$3.0 \times 10^8\ \text{m s}^{-1}$` },
  { id: 'ph-alpha', topic: 'P7', front: t`Effect of alpha and beta-minus decay on $A$ and $Z$`, back: t`Alpha: $A - 4$, $Z - 2$. Beta-minus: $A$ unchanged, $Z + 1$.` },
  { id: 'ph-ionising', topic: 'P7', front: 'Order of ionising and penetrating power', back: 'Ionising: alpha > beta > gamma. Penetrating: gamma > beta > alpha.' },
  { id: 'ph-halflife', topic: 'P7', front: t`After $n$ half-lives, the ratio of stable daughter to parent`, back: t`$(2^n - 1) : 1$` },
];

export const FLASHCARDS: Flashcard[] = [
  ...M1.map((c) => ({ ...c, deck: 'M1' as const })),
  ...PH.map((c) => ({ ...c, deck: 'PH' as const })),
  ...M2.map((c) => ({ ...c, deck: 'M2' as const })),
];
