import type { ModuleId } from './types';

/**
 * Every assessable point of the ESAT content specification for assessment in
 * October 2026 and January 2027 (Mathematics 1, Physics, Mathematics 2), at
 * the finest level the specification itself lists. Question `spec` tags must
 * be codes from this list, and the tests require every point to be tested by
 * at least one question across the mock papers.
 */
export interface SpecPoint {
  code: string;
  module: ModuleId;
  /** Topic code, e.g. "M5", "P3", "MM6". */
  topic: string;
  text: string;
}

const M1: [string, string][] = [
  ['M1.1', 'Standard units and compound units: speed, rates of pay, unit pricing, density, pressure'],
  ['M1.2', 'Changing between related units and compound units, numerically and algebraically'],
  ['M2.1', 'Ordering integers, decimals and fractions; the symbols =, ≠, <, >, ≤, ≥'],
  ['M2.2', 'The four operations with integers, decimals, fractions and mixed numbers; place value'],
  ['M2.3', 'Primes, factors, multiples, HCF, LCM and prime factorisation'],
  ['M2.4', 'Inverse operations, cancellation and the priority of operations'],
  ['M2.5', 'Systematic listing and the product rule for counting'],
  ['M2.6', 'Squares, positive and negative square roots, cubes and cube roots'],
  ['M2.7', 'Index laws with integer, fractional and negative powers'],
  ['M2.8', 'Standard form'],
  ['M2.9', 'Terminating and recurring decimals, fractions and percentages'],
  ['M2.10', 'Fractions, decimals and percentages in calculations; equivalent fractions'],
  ['M2.11', 'Exact calculation with fractions, surds and π; rationalising denominators'],
  ['M2.12', 'Upper and lower bounds in calculations and contexts'],
  ['M2.13', 'Rounding, significant figures and error intervals from rounding or truncation'],
  ['M2.14', 'Estimation, including expressions involving π and surds'],
  ['M3.1', 'Scale factors, scale diagrams and maps'],
  ['M3.2', 'One quantity as a fraction of another'],
  ['M3.3', 'Ratio notation'],
  ['M3.4', 'Dividing a quantity in a given ratio'],
  ['M3.5', 'Ratio in context: conversion, comparison, scaling, mixing and concentration'],
  ['M3.6', 'Proportion; ratios as fractions and as linear functions'],
  ['M3.7', 'Fractions in ratio problems'],
  ['M3.8', 'Percentages, percentage change, original values and simple interest'],
  ['M3.9', 'Direct and inverse proportion, including powers and graphs'],
  ['M3.10', 'Comparing lengths, areas and volumes; similarity and scale factors'],
  ['M3.11', 'Growth and decay, compound interest and iterative processes'],
  ['M4.1', 'Algebraic notation'],
  ['M4.2', 'Index laws in algebra'],
  ['M4.3', 'Substituting into formulae; expressions, equations, formulae, identities'],
  ['M4.4', 'Expanding brackets and taking out common factors'],
  ['M4.5', 'Factorising quadratics, including the difference of two squares'],
  ['M4.6', 'Simplifying and combining algebraic fractions'],
  ['M4.7', 'Rearranging formulae'],
  ['M4.8', 'Equations versus identities; showing expressions are equivalent'],
  ['M4.9', 'Coordinates in all four quadrants'],
  ['M4.10', 'Straight lines: gradients, intercepts, parallel and perpendicular lines'],
  ['M4.11', 'Roots, intercepts and turning points of quadratics; completing the square'],
  ['M4.12a', 'Graphs of linear functions'],
  ['M4.12b', 'Graphs of quadratic functions'],
  ['M4.12c', 'Graphs of simple cubic functions'],
  ['M4.12d', 'The reciprocal graph y = 1/x'],
  ['M4.12e', 'Exponential graphs y = kˣ'],
  ['M4.12f', 'Graphs of sin, cos and tan in degrees'],
  ['M4.13', 'Interpreting graphs in real contexts'],
  ['M4.14', 'Gradients of and areas under graphs, including distance–time and speed–time'],
  ['M4.15', 'Forming and solving simultaneous equations, including linear–quadratic'],
  ['M4.16', 'Solving quadratic equations'],
  ['M4.17', 'Linear inequalities in one or two variables; regions'],
  ['M4.18', 'Term-to-term and position-to-term rules'],
  ['M4.19', 'The nth term of linear and quadratic sequences'],
  ['M5.1', 'Geometric terms; polygons and their symmetries'],
  ['M5.2', 'Angle facts; parallel lines; interior and exterior angles of polygons'],
  ['M5.3', 'Properties of special quadrilaterals and triangles'],
  ['M5.4', 'Congruence criteria: SSS, SAS, ASA, RHS'],
  ['M5.5', 'Reasoning with angle facts, congruence and similarity'],
  ['M5.6', 'Transformations and their combinations; translation vectors'],
  ['M5.7', 'Pythagoras’ theorem in two and three dimensions'],
  ['M5.8', 'Circle terms: chord, tangent, arc, sector, segment, major and minor'],
  ['M5.9a', 'Circle theorem: angle at the centre is twice the angle at the circumference'],
  ['M5.9b', 'Circle theorem: the angle in a semicircle is 90°'],
  ['M5.9c', 'Circle theorem: angles in the same segment are equal'],
  ['M5.9d', 'Circle theorem: the alternate segment theorem'],
  ['M5.9e', 'Circle theorem: a tangent is perpendicular to the radius'],
  ['M5.9f', 'Circle theorem: cyclic quadrilaterals'],
  ['M5.10', 'Geometry on coordinate axes'],
  ['M5.11', 'Faces, surfaces, edges and vertices of 3D shapes'],
  ['M5.12', 'Plans and elevations'],
  ['M5.13', 'Maps, scale drawings and three-figure bearings'],
  ['M5.14', 'Areas of triangles, parallelograms and trapezia; volumes of prisms'],
  ['M5.15', 'Circles, cylinders, spheres, cones, pyramids and composite shapes'],
  ['M5.16', 'Arc lengths and sector areas'],
  ['M5.17', 'Similar figures: lengths, areas and volumes'],
  ['M5.18', 'Trigonometric ratios and exact values in 2D and 3D'],
  ['M5.19', 'Vectors: addition, scalar multiples and geometric arguments'],
  ['M6.1a', 'Two-way tables, bar charts, pie charts and pictograms'],
  ['M6.1b', 'Vertical line charts'],
  ['M6.1c', 'Time series tables and line graphs'],
  ['M6.2a', 'Histograms with equal and unequal class widths; frequency density'],
  ['M6.2b', 'Cumulative frequency graphs'],
  ['M6.3', 'Averages, range, quartiles and IQR; grouped estimates; comparing distributions'],
  ['M6.4', 'Scatter graphs, correlation and causation, lines of best fit'],
  ['M7.1', 'Frequency tables and frequency trees'],
  ['M7.2', 'Expected outcomes, randomness and fairness'],
  ['M7.3', 'Relative frequency and theoretical probability'],
  ['M7.4', 'Exhaustive, mutually exclusive outcomes sum to 1'],
  ['M7.5', 'Systematic enumeration with tables, grids, Venn diagrams and tree diagrams'],
  ['M7.6', 'Sample spaces for single and combined experiments'],
  ['M7.7a', 'Combined events: independent outcomes'],
  ['M7.7b', 'Combined events: dependent outcomes and conditional probability'],
];

const PH: [string, string][] = [
  ['P1.1a', 'Insulators can be charged by friction'],
  ['P1.1b', 'Charging is caused by the gain or loss of electrons'],
  ['P1.1c', 'Like charges repel and unlike charges attract'],
  ['P1.1d', 'Applications and hazards of electrostatics; earthing'],
  ['P1.2a', 'Circuit symbols and diagrams'],
  ['P1.2b', 'Alternating and direct current'],
  ['P1.2c', 'Electrical conductors and insulators'],
  ['P1.2d', 'Current and charge: I = Q/t'],
  ['P1.2e', 'Using ammeters and voltmeters'],
  ['P1.2f', 'Resistance: R = V/I'],
  ['P1.2g', 'V–I graphs of a fixed resistor and a filament lamp'],
  ['P1.2h', 'NTC thermistors, LDRs and ideal diodes'],
  ['P1.2i', 'Current and voltage rules in series and parallel circuits'],
  ['P1.2j', 'Total resistance in series'],
  ['P1.2k', 'Parallel resistance is less than any single resistor'],
  ['P1.2l', 'Voltage and energy: V = E/Q'],
  ['P1.2m', 'Power: P = IV = I²R'],
  ['P1.2n', 'Energy transferred: E = VIt'],
  ['P2.1a', 'Magnetic poles, attraction and repulsion'],
  ['P2.1b', 'The field pattern of a bar magnet'],
  ['P2.1c', 'Soft and hard magnetic materials'],
  ['P2.1d', 'Induced magnetism'],
  ['P2.2a', 'The magnetic effect of a current'],
  ['P2.2b', 'Field patterns around straight wires and solenoids'],
  ['P2.2c', 'Factors affecting the field strength around a wire'],
  ['P2.2d', 'Permanent magnets and electromagnets'],
  ['P2.3a', 'A current-carrying wire in a magnetic field can feel a force'],
  ['P2.3b', 'Direction of the force: the left-hand rule'],
  ['P2.3c', 'Factors affecting the size of the force'],
  ['P2.3d', 'F = BIL'],
  ['P2.3e', 'The dc motor'],
  ['P2.3f', 'Applications of electromagnets'],
  ['P2.4a', 'Induction by cutting field lines or a changing field'],
  ['P2.4b', 'Factors affecting the size of an induced voltage'],
  ['P2.4c', 'Factors affecting the direction of an induced voltage'],
  ['P2.4d', 'The ac generator and its output'],
  ['P2.4e', 'Graphs of generator output'],
  ['P2.4f', 'Applications of electromagnetic induction'],
  ['P2.5a', 'Step-up and step-down transformers'],
  ['P2.5b', 'Turns ratio: Vp/Vs = np/ns'],
  ['P2.5c', 'Ideal transformer power: VpIp = VsIs'],
  ['P2.5d', 'Power transmission and losses'],
  ['P3.1a', 'Scalar and vector quantities'],
  ['P3.1b', 'Distance and displacement; speed and velocity'],
  ['P3.1c', 'Speed and velocity equations'],
  ['P3.1d', 'Acceleration'],
  ['P3.1e', 'Interpreting motion graphs'],
  ['P3.1f', 'Gradients and areas under motion graphs'],
  ['P3.1g', 'Average speed'],
  ['P3.1h', 'v² − u² = 2as'],
  ['P3.2a', 'Types of force'],
  ['P3.2b', 'Factors affecting the size and direction of forces'],
  ['P3.2c', 'Force diagrams'],
  ['P3.2d', 'Resultant force in one dimension'],
  ['P3.3a', 'Force–extension graphs'],
  ['P3.3b', 'Elastic and inelastic extension; elastic limit'],
  ['P3.3c', 'Hooke’s law and the limit of proportionality'],
  ['P3.3d', 'Energy stored in a spring'],
  ['P3.4a', 'Newton’s first law'],
  ['P3.4b', 'Mass and inertia'],
  ['P3.4c', 'Newton’s second law'],
  ['P3.4d', 'Newton’s third law'],
  ['P3.5a', 'Mass and weight'],
  ['P3.5b', 'Gravitational field strength g = 10 N kg⁻¹'],
  ['P3.5c', 'Weight: w = mg'],
  ['P3.5d', 'Free-fall acceleration'],
  ['P3.5e', 'Factors affecting air resistance'],
  ['P3.5f', 'Terminal velocity'],
  ['P3.6a', 'Momentum: p = mv'],
  ['P3.6b', 'Conservation of momentum'],
  ['P3.6c', 'Force as rate of change of momentum'],
  ['P3.7a', 'Work = force × distance'],
  ['P3.7b', 'Work as energy transfer'],
  ['P3.7c', 'Gravitational potential energy'],
  ['P3.7d', 'Kinetic energy'],
  ['P3.7e', 'Power'],
  ['P3.7f', 'Conservation of energy'],
  ['P3.7g', 'Useful and wasted energy'],
  ['P3.7h', 'Efficiency'],
  ['P4.1a', 'Thermal conductors and insulators'],
  ['P4.1b', 'Factors affecting the rate of conduction'],
  ['P4.2a', 'Temperature and fluid density'],
  ['P4.2b', 'Convection currents'],
  ['P4.3a', 'Thermal radiation as infrared'],
  ['P4.3b', 'Absorption and emission of radiation'],
  ['P4.3c', 'Factors affecting absorption and emission'],
  ['P4.4a', 'Energy transfer and temperature change'],
  ['P4.4b', 'Specific heat capacity'],
  ['P5.1a', 'Properties of solids, liquids and gases'],
  ['P5.1b', 'Particle models of the states of matter'],
  ['P5.1c', 'Explaining properties with particle motion, forces and spacing'],
  ['P5.2a', 'Gas pressure and temperature in terms of particles'],
  ['P5.2b', 'Boyle’s law: PV = constant'],
  ['P5.3a', 'Melting point and boiling point'],
  ['P5.3b', 'Latent heat of fusion and of vaporisation'],
  ['P5.3c', 'Specific latent heat calculations'],
  ['P5.4a', 'Density: ρ = m/V'],
  ['P5.4b', 'Measuring density'],
  ['P5.4c', 'Densities of solids, liquids and gases'],
  ['P5.5a', 'Pressure = force/area'],
  ['P5.5b', 'Hydrostatic pressure ρgh'],
  ['P6.1a', 'Waves transfer energy without net movement of matter'],
  ['P6.1b', 'Transverse and longitudinal waves'],
  ['P6.1c', 'Peak, trough, compression and rarefaction'],
  ['P6.1d', 'Examples of waves'],
  ['P6.1e', 'Amplitude, wavelength, frequency and period'],
  ['P6.1f', 'f = 1/T'],
  ['P6.1g', 'Wave speed = distance/time'],
  ['P6.1h', 'v = fλ'],
  ['P6.2a', 'Reflection'],
  ['P6.2b', 'Refraction'],
  ['P6.2c', 'Effect of reflection and refraction on speed, frequency, wavelength and direction'],
  ['P6.2d', 'Light and water waves compared'],
  ['P6.2e', 'The Doppler effect'],
  ['P6.3a', 'Ray diagrams for plane mirrors'],
  ['P6.3b', 'Angle of incidence = angle of reflection'],
  ['P6.3c', 'Ray diagrams for refraction at a plane boundary'],
  ['P6.3d', 'Angles of incidence and refraction'],
  ['P6.3e', 'Refraction towards or away from the normal'],
  ['P6.4a', 'Sound from a vibrating source'],
  ['P6.4b', 'Sound needs a medium'],
  ['P6.4c', 'Loudness and amplitude; pitch and frequency'],
  ['P6.4d', 'Sound as a longitudinal wave'],
  ['P6.4e', 'Echoes'],
  ['P6.4f', 'Human hearing: 20 Hz to 20 kHz'],
  ['P6.4g', 'Ultrasound: sonar and medical scanning'],
  ['P6.5a', 'Nature of electromagnetic waves'],
  ['P6.5b', 'Parts of the electromagnetic spectrum'],
  ['P6.5c', 'Wavelength and frequency across the spectrum'],
  ['P6.5d', 'Order of the spectrum'],
  ['P6.5e', 'Applications and hazards of electromagnetic waves'],
  ['P7.1a', 'Protons, neutrons and electrons'],
  ['P7.1b', 'The nuclear model of the atom'],
  ['P7.1c', 'Relative charges and masses of subatomic particles'],
  ['P7.1d', 'Atomic number and mass number'],
  ['P7.1e', 'Isotopes'],
  ['P7.1f', 'Nuclides and nuclide notation'],
  ['P7.1g', 'Ionisation as gain or loss of electrons'],
  ['P7.2a', 'Emissions come from unstable nuclei'],
  ['P7.2b', 'The random nature of decay'],
  ['P7.2c', 'Alpha, beta and gamma emission compared'],
  ['P7.2d', 'The nature of alpha, beta and gamma radiation'],
  ['P7.2e', 'Nuclear equations'],
  ['P7.2f', 'Effect of decay on atomic and mass numbers'],
  ['P7.3a', 'Penetrating abilities'],
  ['P7.3b', 'Ionising abilities'],
  ['P7.3c', 'Deflection in electric and magnetic fields'],
  ['P7.3d', 'Background radiation'],
  ['P7.3e', 'Applications and hazards of ionising radiation'],
  ['P7.4a', 'Decay graphs, including decay products'],
  ['P7.4b', 'The meaning of half-life'],
  ['P7.4c', 'Half-life calculations'],
];

const M2: [string, string][] = [
  ['MM1.1', 'Laws of indices for rational exponents'],
  ['MM1.2', 'Surds and rationalising denominators'],
  ['MM1.3', 'Quadratics: graphs, the discriminant, completing the square, solving'],
  ['MM1.4', 'Simultaneous equations: one linear and one quadratic'],
  ['MM1.5', 'Linear and quadratic inequalities'],
  ['MM1.6a', 'Expanding brackets and collecting like terms'],
  ['MM1.6b', 'Factorising and algebraic division by linear and quadratic divisors'],
  ['MM1.6c', 'The factor and remainder theorems'],
  ['MM1.7', 'Functions: one-to-one and many-to-one; √x and |x|'],
  ['MM2.1', 'Sequences from nth-term formulas and recurrence relations'],
  ['MM2.2', 'Arithmetic series; the sum of the first n natural numbers'],
  ['MM2.3', 'Geometric series and sums to infinity'],
  ['MM2.4', 'The binomial expansion; n! and nCr'],
  ['MM3.1', 'Straight lines in several forms; parallel and perpendicular lines'],
  ['MM3.2a', 'Circles in the form (x − a)² + (y − b)² = r²'],
  ['MM3.2b', 'Circles in the form x² + y² + cx + dy + e = 0'],
  ['MM3.3a', 'The perpendicular from the centre bisects a chord'],
  ['MM3.3b', 'A tangent is perpendicular to the radius'],
  ['MM3.3c', 'Angle at the centre is twice the angle at the circumference'],
  ['MM3.3d', 'The angle in a semicircle is a right angle'],
  ['MM3.3e', 'Angles in the same segment are equal'],
  ['MM3.3f', 'Opposite angles of a cyclic quadrilateral sum to 180°'],
  ['MM3.3g', 'The alternate segment theorem'],
  ['MM4.1', 'Sine and cosine rules, ½ab sin C, the ambiguous case, 3D problems'],
  ['MM4.2', 'Radians: arc length, sector and segment area'],
  ['MM4.3', 'Exact values of sin, cos and tan'],
  ['MM4.4', 'Graphs of sin, cos and tan: symmetry and periodicity'],
  ['MM4.5a', 'tan θ = sin θ / cos θ'],
  ['MM4.5b', 'sin²θ + cos²θ = 1'],
  ['MM4.6', 'Trigonometric equations in a given interval'],
  ['MM5.1', 'y = aˣ and its graph'],
  ['MM5.2', 'The laws of logarithms'],
  ['MM5.3', 'Solving aˣ = b, including after manipulation'],
  ['MM6.1', 'The derivative as the gradient of a tangent; notation'],
  ['MM6.1a', 'The derivative as a rate of change'],
  ['MM6.1b', 'Second derivatives'],
  ['MM6.2', 'Differentiating xⁿ for rational n, after simplifying'],
  ['MM6.3', 'Tangents, normals, stationary points, increasing and decreasing functions'],
  ['MM7.1', 'Definite integrals and the area between a curve and an axis'],
  ['MM7.2', 'Integrating xⁿ for rational n ≠ −1, after simplifying'],
  ['MM7.3a', 'Fundamental theorem: the integral from a to b is F(b) − F(a)'],
  ['MM7.3b', 'Fundamental theorem: d/dx of the integral from a to x is f(x)'],
  ['MM7.4', 'Combining integrals over equal or contiguous ranges'],
  ['MM7.5', 'The trapezium rule; over- and underestimates'],
  ['MM7.6', 'Differential equations dy/dx = f(x)'],
  ['MM8.1', 'Recognising and sketching common graphs'],
  ['MM8.2', 'Compositions of transformations; the notation f(g(x))'],
  ['MM8.2a', 'Transformation y = a f(x)'],
  ['MM8.2b', 'Transformation y = f(x) + a'],
  ['MM8.2c', 'Transformation y = f(x + a)'],
  ['MM8.2d', 'Transformation y = f(ax)'],
  ['MM8.3', 'The effect of m and c on y = mx + c'],
  ['MM8.4', 'The effect of a, b and c on y = a(x + b)² + c'],
  ['MM8.5a', 'Using stationary points to find the shape of a graph'],
  ['MM8.5b', 'Where a graph is increasing or decreasing'],
  ['MM8.6', 'Intersections with the axes; possible numbers of real roots'],
  ['MM8.7', 'Intersections of graphs and simultaneous equations'],
];

const topicOf = (code: string) => code.split('.')[0];

export const SPEC: SpecPoint[] = [
  ...M1.map(([code, text]): SpecPoint => ({ code, text, module: 'M1', topic: topicOf(code) })),
  ...PH.map(([code, text]): SpecPoint => ({ code, text, module: 'PH', topic: topicOf(code) })),
  ...M2.map(([code, text]): SpecPoint => ({ code, text, module: 'M2', topic: topicOf(code) })),
];

export const SPEC_BY_CODE: Map<string, SpecPoint> = new Map(SPEC.map((p) => [p.code, p]));
